# Form implementation generated from reading ui file 'config_gerador.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import QSize, QRect
from PyQt6.QtWidgets import QDialog, QLabel,  QPushButton, QHBoxLayout, QWidget,QLineEdit
from funcoes_utils import windowCreate, fontCreate

font = fontCreate()
class ConfigGerador(QDialog):
    def __init__(self):
        super().__init__()
        
        windowCreate(self, 400,300, "Config-Gerador")

        self.label = QLabel(parent=self)
        self.label.setGeometry(QRect(0, 0, 400, 300))
        self.label.setMinimumSize(QSize(400, 300))
        self.label.setStyleSheet("background-image: url(files/icon_Dialog.png);")
        self.label.setText("")
        
        self.layoutWidget = QWidget(parent=self)
        self.layoutWidget.setGeometry(QRect(220, 260, 168, 30))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        
        self.buttonAplicar = QPushButton(parent=self.layoutWidget)
        self.buttonAplicar.setFont(font)
        self.buttonAplicar.setText("Cancelar")
        self.buttonAplicar.clicked.connect(self.closeWindow)
        self.horizontalLayout.addWidget(self.buttonAplicar)
        
        self.buttonCancelar = QPushButton(parent=self.layoutWidget)
        self.buttonCancelar.clicked.connect(self.closeWindow)
        self.buttonCancelar.setText("Cancelar")
        self.buttonCancelar.setFont(font)
        self.horizontalLayout.addWidget(self.buttonCancelar)

        self.labelAmplitude = QLabel(parent=self)
        self.labelAmplitude.setGeometry(QRect(20, 60, 91, 17))
        self.labelAmplitude.setFont(font)
        self.labelAmplitude.setText("Amplitude")
        self.lineEditAmpli = QLineEdit(parent=self)
        self.lineEditAmpli.setGeometry(QRect(20, 80, 113, 25))

        self.labelFreq = QLabel(parent=self)
        self.labelFreq.setGeometry(QRect(20, 130, 91, 17))
        self.labelFreq.setFont(font)
        self.labelFreq.setText("Frequência")
        
        self.lineEditFreq = QLineEdit(parent=self)
        self.lineEditFreq.setGeometry(QRect(20, 150, 113, 25))

    def showWindow(self):
        self.exec()
    def closeWindow(self):
        self.close()